"""Add system_prompt to Business

Revision ID: 799c9d6d19f0
Revises: b25db1c0eecd
Create Date: 2025-07-02 13:27:36.355635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799c9d6d19f0'
down_revision: Union[str, None] = 'b25db1c0eecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'system_prompt')
    # ### end Alembic commands ###
